__version__ = "1.3.1"
__author__ = "Artem Onyshchenko"
__email__ = "artemon888.com@gmail.com"
__license__ = "MIT"
__url__ = "https://github.com/Artemon0/UsableFunctions.git"
__download_url__ = "https://github.com/Artemon0/UsableFunctions/archive/refs/tags/1.3.1.tar.gz"
